//! Injects `shaders/preprocess.wgsl` into the wasm inline_js block at build
//! time (single-source WGSL contract, r4 §3).
//!
//! Output: `$OUT_DIR/ort_bridge_generated.rs` — a full `#[wasm_bindgen(inline_js
//! = "...")]` extern block that `src/ort_bridge.rs` picks up via `include!`.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=shaders/preprocess.wgsl");
    println!("cargo:rerun-if-changed=src/ort_bridge_template.js");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR unset"));
    let out_rs  = out_dir.join("ort_bridge_generated.rs");

    // Only produce a meaningful generated file for wasm32 targets. For native
    // builds the caller doesn't `include!` this at all (ort_bridge.rs is
    // cfg(target_arch = "wasm32")), but write a placeholder so out-of-tree
    // `cargo check` on wrong targets still succeeds.
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    if target_arch != "wasm32" {
        fs::write(&out_rs, "// non-wasm target; ort_bridge module is cfg-out.\n")
            .expect("failed to write placeholder ort_bridge_generated.rs");
        return;
    }

    let wgsl = fs::read_to_string("shaders/preprocess.wgsl")
        .expect("shaders/preprocess.wgsl missing");
    let tpl = fs::read_to_string("src/ort_bridge_template.js")
        .expect("src/ort_bridge_template.js missing");

    // The WGSL will be embedded as a JS template literal
    // (`const PREPROCESS_WGSL = \`...\`;`), so escape template-literal
    // metacharacters: backslash, backtick, and `${`.
    let wgsl_js = wgsl
        .replace('\\', "\\\\")
        .replace('`', "\\`")
        .replace("${", "\\${");
    // Enforce single-occurrence: template comments must not contain the raw
    // sentinel (they can describe the mechanism obliquely — see the header
    // in ort_bridge_template.js). If this fires, the template got out of sync.
    let sentinel = "__PREPROCESS_WGSL__";
    let count = tpl.matches(sentinel).count();
    assert_eq!(
        count, 1,
        "ort_bridge_template.js must contain exactly one `{sentinel}`; found {count}. \
         Comments referencing the mechanism must not include the literal sentinel.",
    );
    let js = tpl.replace(sentinel, &wgsl_js);

    // Encode the entire JS blob as a Rust raw string literal for
    // #[wasm_bindgen(inline_js = r#"..."#)]. Grow the `#`-count until no
    // interior `"###...` sequence collides with the delimiter.
    let mut hashes = 1usize;
    loop {
        let needle = format!("\"{}", "#".repeat(hashes));
        if !js.contains(&needle) {
            break;
        }
        hashes += 1;
    }
    let d = "#".repeat(hashes);

    // Assemble the Rust source by string concatenation (avoiding format!'s `{}`
    // clashing with JS syntax).
    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — do not edit.\n");
    out.push_str("// The inline_js payload is src/ort_bridge_template.js with\n");
    out.push_str("// shaders/preprocess.wgsl substituted for __PREPROCESS_WGSL__.\n\n");
    out.push_str("use wasm_bindgen::prelude::*;\n\n");

    out.push_str("#[wasm_bindgen(inline_js = r");
    out.push_str(&d);
    out.push('"');
    out.push_str(&js);
    out.push('"');
    out.push_str(&d);
    out.push_str(")]\n");

    out.push_str("extern \"C\" {\n");
    out.push_str("    pub fn capture_webgpu_device();\n\n");

    out.push_str("    #[wasm_bindgen(catch)]\n");
    out.push_str("    pub async fn ort_init(model_url: &str) -> Result<JsValue, JsValue>;\n\n");

    out.push_str("    /// Main-line API: hand in a `GPUBuffer` extracted from a\n");
    out.push_str("    /// `wgpu::Buffer` (same GPUDevice). Returns the raw model output\n");
    out.push_str("    /// tensor as a JS `Float32Array` (wrapped in `JsValue`).\n");
    out.push_str("    #[wasm_bindgen(catch)]\n");
    out.push_str("    pub async fn ort_run_gpu_buffer(\n");
    out.push_str("        gpu_buffer: &web_sys::GpuBuffer,\n");
    out.push_str("        dims: js_sys::Array,\n");
    out.push_str("    ) -> Result<JsValue, JsValue>;\n\n");

    out.push_str("    /// Fallback API: hand in a host `Float32Array`.\n");
    out.push_str("    #[wasm_bindgen(catch)]\n");
    out.push_str("    pub async fn ort_run_cpu_slice(\n");
    out.push_str("        nchw: &js_sys::Float32Array,\n");
    out.push_str("        dims: js_sys::Array,\n");
    out.push_str("    ) -> Result<JsValue, JsValue>;\n\n");

    out.push_str("    /// Transition API for open_quartz and other canvas-based debug\n");
    out.push_str("    /// tools. Main-line callers MUST NOT use this. Returns a JS dict\n");
    out.push_str("    /// `{ output: Float32Array, scale, padX, padY, srcW, srcH }`.\n");
    out.push_str("    #[wasm_bindgen(catch)]\n");
    out.push_str("    pub async fn ort_detect(\n");
    out.push_str("        canvas: &web_sys::HtmlCanvasElement,\n");
    out.push_str("    ) -> Result<JsValue, JsValue>;\n\n");

    out.push_str("    pub fn ort_release();\n");
    out.push_str("}\n");

    fs::write(&out_rs, out).expect("failed to write ort_bridge_generated.rs");
}
