//! wasm-only inference bridge to onnxruntime-web.
//!
//! The `#[wasm_bindgen(inline_js = ...)]` extern block is generated by
//! `build.rs` from `src/ort_bridge_template.js` + `shaders/preprocess.wgsl` —
//! this way the JS-side canvas path's compute shader is the SAME source of
//! truth as the Rust-side `PreprocessPipeline` (r4 §3 contract).
//!
//! # Function inventory
//!
//! | Function                              | Path                | Consumer                     |
//! |---------------------------------------|---------------------|------------------------------|
//! | `capture_webgpu_device()`             | shared              | call once before wgpu init   |
//! | `ort_init(model_url)`                 | shared              | one-time model load          |
//! | `ort_run_gpu_buffer(gpu_buffer, dims)`| main-line, Tier A   | RimeCut wasm main-line       |
//! | `ort_run_cpu_slice(nchw, dims)`       | main-line fallback  | RimeCut when HAL unavailable |
//! | `ort_detect(canvas)`                  | transition, Tier C  | open_quartz debug tools      |
//! | `ort_release()`                       | shared              | teardown                     |
//!
//! # Main-line usage
//!
//! ```ignore
//! use rimeflow_yolov8n::{
//!     ort_bridge,
//!     preprocess::{LetterboxParams, PreprocessPipeline},
//!     postprocess::{decode_yolo_output, nms},
//!     MODEL_URL, INPUT_SHAPE,
//! };
//!
//! ort_bridge::capture_webgpu_device();  // before wgpu Instance/Adapter/Device init
//! ort_bridge::ort_init(MODEL_URL).await?;
//!
//! let pipeline = PreprocessPipeline::new(&device, 640, PreprocessPipeline::default_buffer_usage());
//! // ... each frame ...
//! let letterbox = LetterboxParams::compute(src_w, src_h, 640);
//! let mut enc = device.create_command_encoder(&Default::default());
//! pipeline.dispatch(&device, &queue, &mut enc, &scene_view, letterbox);
//! queue.submit(Some(enc.finish()));
//!
//! let raw = if let Some(gpu_buf) = ort_bridge::extract_web_gpu_buffer(pipeline.output()) {
//!     let dims = js_sys::Array::of4(&1.into(), &3.into(), &640.into(), &640.into());
//!     let js = ort_bridge::ort_run_gpu_buffer(&gpu_buf, dims).await?;
//!     js_sys::Float32Array::from(js).to_vec()
//! } else {
//!     // Fallback: readback + ort_run_cpu_slice (see extract_web_gpu_buffer docs)
//!     unimplemented!("wgpu HAL escape hatch unavailable — see extract_web_gpu_buffer docs")
//! };
//!
//! let dets = decode_yolo_output(&raw, src_w, src_h, letterbox.scale,
//!                               letterbox.pad_x_px(), letterbox.pad_y_px());
//! let filtered = nms(&dets, 0.45);
//! ```
//!
//! # Transition (open_quartz) usage
//!
//! ```ignore
//! use rimeflow_yolov8n::{
//!     ort_bridge::{self, get_output_f32, get_f64},
//!     postprocess::{decode_yolo_output, nms},
//!     MODEL_URL,
//! };
//!
//! ort_bridge::capture_webgpu_device();
//! ort_bridge::ort_init(MODEL_URL).await?;
//! let result = ort_bridge::ort_detect(&canvas).await?;
//!
//! // Canvas GPU sub-path may race with the compositor's canvas backing
//! // texture (WebGPU-backed canvases invalidate at end of anim-frame task).
//! // On race the JS side returns `null`; caller advances its own state
//! // (e.g. Kalman-only prediction) without running detection this cycle.
//! if result.is_null() {
//!     return; // or: advance tracker without an IoU association step
//! }
//!
//! let raw    = get_output_f32(&result, "output").unwrap();
//! let scale  = get_f64(&result, "scale") as f32;
//! let pad_x  = get_f64(&result, "padX")  as f32;   // ALREADY in pixel units
//! let pad_y  = get_f64(&result, "padY")  as f32;
//! let src_w  = get_f64(&result, "srcW")  as u32;
//! let src_h  = get_f64(&result, "srcH")  as u32;
//!
//! let dets = decode_yolo_output(&raw, src_w, src_h, scale, pad_x, pad_y);
//! let filtered = nms(&dets, 0.45);
//! ```

#![cfg(target_arch = "wasm32")]

// The wasm_bindgen(inline_js = ...) extern block is generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/ort_bridge_generated.rs"));

/// Extract the underlying `web_sys::GpuBuffer` from a wgpu::Buffer on the
/// WebGPU backend — the wgpu HAL escape hatch (r4 §4.5).
///
/// The main-line path (`ort_run_gpu_buffer`) requires this to hand a shared
/// `GPUBuffer` reference to `ort.Tensor.fromGpuBuffer`, achieving Tier A
/// zero-copy on the WebGPU EP.
///
/// # Returns
///
/// - `Some(GpuBuffer)` — the underlying JS-side `GPUBuffer`. Safe to pass to
///   `ort_run_gpu_buffer` because it lives on the same `GPUDevice`
///   (guaranteed by the `capture_webgpu_device` monkey-patch installed at
///   startup).
/// - `None` — the current wgpu build does not expose the WebGPU HAL escape
///   hatch. Callers MUST fall back to a manual readback + `ort_run_cpu_slice`.
///
/// # wgpu version compatibility
///
/// - wgpu ≤ 24: WebGPU HAL is `pub(crate)`. This function returns `None`.
///   The RimeCut monorepo maintains a tiny patch under `rust/crates/gpu` that
///   unlocks the path.
/// - wgpu ≥ 25 (expected): `Buffer::as_hal::<hal::api::WebGpu>()` will be
///   public. Swap this function body to use it directly.
pub fn extract_web_gpu_buffer(_buf: &wgpu::Buffer) -> Option<web_sys::GpuBuffer> {
    // TODO: once wgpu exposes the WebGPU HAL publicly, implement as:
    //   unsafe {
    //     _buf.as_hal::<wgpu_hal::api::WebGpu>()
    //         .map(|h| h.raw_buffer().clone())
    //   }
    None
}

/// Parse a `Float32Array` field out of the JS dict returned by `ort_detect`.
pub fn get_output_f32(result: &wasm_bindgen::JsValue, key: &str) -> Option<Vec<f32>> {
    let val = js_sys::Reflect::get(result, &wasm_bindgen::JsValue::from_str(key)).ok()?;
    Some(js_sys::Float32Array::from(val).to_vec())
}

/// Parse a numeric field out of the JS dict returned by `ort_detect`.
pub fn get_f64(result: &wasm_bindgen::JsValue, key: &str) -> f64 {
    js_sys::Reflect::get(result, &wasm_bindgen::JsValue::from_str(key))
        .ok()
        .and_then(|v| v.as_f64())
        .unwrap_or(0.0)
}
