import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const entries = [];
const fixtures = JSON.parse(await readFile(resolve(root, 'evidence/fixtures/manifest.json'), 'utf8'));
const paths = [
  'models/yolov8n.onnx',
  'evidence/model/model-contract.json',
  'evidence/fixtures/manifest.json',
  'evidence/fixtures/THIRD_PARTY_NOTICES.md',
  'evidence/fixtures/licenses/ultralytics-assets-AGPL-3.0.txt',
  ...new Set(fixtures.images.flatMap((item) => [item.path, typeof item.source === 'object' ? item.source.path : null]).filter(Boolean)),
  ...fixtures.rawTensorFixtures.map((item) => item.path),
  'evidence/golden/coverage-matrix.json',
  'evidence/golden/web-reference.json',
  'evidence/conversions/conversion-spikes.json',
  'evidence/conversions/coreml-artifact-manifest.json',
  'evidence/conversions/litert-artifact-manifest.json',
  'evidence/conversions/mindspore-artifact-manifest.json',
  'evidence/conversions/windows-ml-spike-manifest.json',
  'evidence/conversions/openvino-ep-manifest.json',
  'evidence/conversions/cuda-ep-spike-manifest.json',
  'evidence/conversions/task1-4-aggregate.json',
  'evidence/reports/windows-ml-spike-report.json',
  'evidence/reports/windows-ml-static-compile-report.json',
  'evidence/reports/openvino-ep-report.json',
  'evidence/reports/cuda-ep-spike-report.json',
  'evidence/reports/tensorrt-ep-report.json',
  'evidence/reports/handoff-model-audit.json',
  'evidence/reports/model-provenance.json',
  'evidence/reports/preprocess-conformance.json',
  'evidence/reports/coreml-conversion-report.json',
  'evidence/reports/litert-conversion-report.json',
  'evidence/reports/litert-golden-report.json',
  'evidence/reports/mindspore-conversion-report.json',
  'evidence/reports/mindspore-golden-report.json',
  'evidence/reports/web-wasm-performance.json',
  'evidence/tooling/requirements.lock',
  'evidence/tooling/model-audit-requirements.lock',
  'evidence/tooling/coreml-requirements.in',
  'evidence/tooling/coreml-requirements.lock',
  'evidence/tooling/litert-requirements.in',
  'evidence/tooling/litert-requirements.lock',
  'evidence/tooling/mindspore-python-addons.lock',
  'evidence/tooling/openvino-requirements.lock',
  'evidence/tooling/cuda-requirements.lock',
  'evidence/tooling/cuda-runner/README.md',
  'evidence/tooling/tensorrt-requirements.lock',
  'evidence/tooling/tensorrt/Dockerfile',
  'evidence/tooling/tensorrt/Dockerfile.dockerignore',
  'evidence/tooling/tensorrt-postprocess/Cargo.toml',
  'evidence/tooling/tensorrt-postprocess/Cargo.lock',
  'evidence/tooling/tensorrt-postprocess/main.rs',
  'evidence/tooling/raw-golden/Cargo.toml',
  'evidence/tooling/raw-golden/Cargo.lock',
  'evidence/tooling/raw-golden/src/lib.rs',
  'evidence/tooling/raw-golden/src/main.rs',
  'src/postprocess.rs',
  'evidence/scripts/evidence_validation.mjs',
  'evidence/scripts/openvino_evidence_validation.mjs',
  'evidence/scripts/openvino_durable_publication.py',
  'evidence/scripts/prepare_openvino_rust_runner.mjs',
  'evidence/scripts/prepare_openvino_tooling.mjs',
  'evidence/scripts/run_openvino_replay.py',
  'evidence/scripts/run_conversion_spikes.mjs',
  'evidence/scripts/test_openvino_publish_transaction.py',
  'evidence/scripts/test_openvino_replay_guards.mjs',
  'evidence/scripts/test_openvino_rust_identity_guards.mjs',
  'evidence/scripts/cuda_evidence_validation.mjs',
  'evidence/scripts/replay_cuda_ep.mjs',
  'evidence/scripts/run_cuda_ep.py',
  'evidence/scripts/test_cuda_ep_guards.mjs',
  'evidence/scripts/validate_cuda_evidence.mjs',
  'evidence/scripts/generate_tensorrt_replay_manifest.mjs',
  'evidence/scripts/replay_tensorrt_ep.mjs',
  'evidence/scripts/run_tensorrt_ep.py',
  'evidence/scripts/run_tensorrt_runner.sh',
  'evidence/scripts/tensorrt_record_publish.py',
  'evidence/scripts/test_tensorrt_ep_negative.mjs',
  'evidence/scripts/test_tensorrt_record_publish.py',
  'evidence/scripts/validate_tensorrt_ep.mjs',
  'evidence/scripts/generate_task14_aggregate.mjs',
  'evidence/scripts/aggregate_evidence_validation.mjs',
  'evidence/tensorrt/contract.json',
  'evidence/scripts/replay_windows_ml_static_compile.mjs',
  'evidence/scripts/test_validator_negative.mjs',
  'evidence/scripts/test_windows_ml_runner_guards.mjs',
  'evidence/scripts/validate_evidence.mjs',
  'evidence/tooling/windows-ml-runner/Program.cs',
  'evidence/tooling/windows-ml-runner/RunnerSupport.cs',
  'evidence/tooling/windows-ml-runner/README.md',
  'evidence/tooling/windows-ml-runner/WindowsMlSpike.csproj',
  'evidence/tooling/windows-ml-runner/global.json',
  'evidence/tooling/windows-ml-runner/packages.lock.json',
  'evidence/tooling/windows-ml-runner-guards/Program.cs',
  'evidence/tooling/windows-ml-runner-guards/WindowsMlRunnerGuards.csproj',
  'evidence/tooling/mindspore-host-runner/main.cpp',
];
for (const path of paths) {
  const bytes = await readFile(resolve(root, path)); entries.push({ path, bytes: bytes.length, sha256: sha256(bytes) });
}
const value = { schemaVersion: 1, sourceCommit: 'eacbcf00dfc2fba941b494e2955e87fffd707382', artifacts: entries };
await writeFile(resolve(root, 'evidence/golden/manifest.json'), JSON.stringify(value, null, 2) + '\n');
console.log(sha256(Buffer.from(JSON.stringify(value, null, 2) + '\n')));
